apiVersion: v1
kind: Service
metadata:
  name:  {{ include "graph_server.fullname" . }}
  annotations:
    var/component: Oracle Graph Visualisierung
    var/name: Oracle Graph Server
    var/shortdesc: 'Oracle Graph Server und Visualisierung -
    Anwendungen, basierend auf einem Tomcat Server, um Graphen 
    in Oracle Datenbanken zu laden und mit SPARQL abzufragen'
spec:
  selector:
   {{- include "graph_server.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
