apiVersion: v1
kind: Service
metadata:
  name:  {{ include "oml4py.fullname" . }}
  annotations:
    var/component: OML4PY jupyter notebook
    var/name: Oracle Machine Learning 4 Python
    var/shortdesc: 'Jupyter Notebook mit vorinstallierter OML4PY
    Bibliothek (Oracle Machine Learning 4 Python)'
spec:
  selector:
      {{- include "oml4py.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
  type: {{ .Values.service.type }}
