apiVersion: v1
kind: Service
metadata:
  name:  {{ include "sqlcl.fullname" . }}
  annotations:
    var/component: SQLCL mit liquibase Kommandozeile
    var/name: sqlcl-liquibase
    var/shortdesc: 'Oracle sqlcl mit integriertem liquibase
    Versionierungstool und Browser-Zugang zur Kommandozeile' 
spec:
  selector:
      {{- include "sqlcl.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.consoleport }}
      targetPort: 8080
      name: console
  type: {{ .Values.service.type }}
