{{- if eq .Values.storage.log.toPVC true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cman.fullname" . }}-log-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storage.log.storageClass }}
  resources:
    requests:
      storage:  {{ .Values.storage.log.storage }}
---
{{- end }}
{{- if eq .Values.storage.config.toPVC true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cman.fullname" . }}-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName:  {{ .Values.storage.config.storageClass }}
  resources:
    requests:
      storage:  {{ .Values.storage.config.storage }}
{{- end }}
