apiVersion: v1
kind: Service
metadata:
  name:  {{ include "cman.fullname" . }}-svc
{{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    oci.oraclecloud.com/load-balancer-type: nlb
{{- end }}
spec:
  ports:
  - name: net8-cman
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 1521
    #- name: https-cman
    #port: 1830
    #protocol: TCP
    #targetPort: 1830
  selector:
    {{- include "cman.selectorLabels" . | nindent 5 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}

