apiVersion: v1
kind: Service
metadata:
  name:  {{ include "oas.fullname" . }}
  annotations:
    var/component: Oracle Analytics Server UI
    var/name: Oracle Analytics Server
    var/shortdesc: 'Oracle Analytics Server Umgebung, 
    benötigt bestehende Oracle Datenbank als Reository bei Einrichtung'
spec:
  selector:
      {{- include "oas.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.consoleport }}
      targetPort: 9500
      name: console
  ports:
    - port: {{ .Values.service.dvport }}
      targetPort: 9502
      name: dv
  type: {{ .Values.service.type }}
