apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "var.fullname" . }}-jupyter-vs
spec:
  gateways:
  - {{ .Values.netzwerk.gateway }}
  hosts:
  - var{{ .Values.netzwerk.suffix }}
  http:
  - match:
    - uri:
        prefix: /jupyter/{{ .Release.Name }}/
    route:
    - destination:
        host: {{ include "var.fullname" . }}-jupyter-service
        port:
          number: 8080

