apiVersion: v1
kind: Service
metadata:
  name: {{ include "var.fullname" . }}-jupyter-service
spec:
  ports:
  - name: jupyter
    port: 8080
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/name: {{ include "var.fullname" . }}-jupyter
  type: ClusterIP

