apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
  name: {{ include "var.fullname" . }}-instantclient-vs
spec:
  gateways:
  - {{ .Values.netzwerk.gateway }}
  hosts:
  - var{{ .Values.netzwerk.suffix }}
  http:
  - match:
    - uri:
        prefix: /sqlplus/{{ .Release.Name }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "var.fullname" . }}-instantclient-svc
        port:
          number: 8080
