apiVersion: v1
kind: Service
metadata:
  name: {{ include "var.fullname" . }}-instantclient-svc
spec:
  ports:
  - name: console
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "var.fullname" . }}-instantclient
  type: ClusterIP
