apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "var.fullname" . }}-cloudbeaver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
