apiVersion: v1
kind: Service
metadata:
  name:  {{ include "var.fullname" . }}-cloudbeaver
  annotations:
    var/component: cloudbeaver
    var/name: raddauerzaehlstellen
    var/shortdesc: 'Anwendungs-Stack mit Datenbank, Analysedaten und Analysewerkzeug,
      hier: Fahrrad-Durchlaufzahlen'
spec:
  selector:
      {{- include "var.selectorLabels" . | nindent 6 }}
  ports:
    - port: 8080
      targetPort: 8978
  type: ClusterIP
{{- if eq .Values.istio.use_istio true }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "var.fullname" . }}-cb-virtservice
spec:
  gateways:
  - {{ .Values.istio.gw }}
  hosts:
  - {{ include "var.fullname" . }}.cb.{{ .Values.istio.domainsuffix }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "var.fullname" . }}-cloudbeaver
        port:
          number: 8080

{{- end }}
