apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.hostname }}
spec:
  selector:
      {{- include "var.selectorLabels" . | nindent 6 }}
      component: db
  ports:
    - port: 1521
      targetPort: 1521
      appProtocol: tcp
      name: dblistener
    - port: 5500
      targetPort: 5500
      appProtocol: https
      name: oem
  type: ClusterIP

