{{- if eq .Values.verrazzano.OAMdeploy true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "var.fullname" . }}-oam-rbac
rules:
  - apiGroups: 
    - ""
    - networking.k8s.io
    - extensions
    resources:
    - secrets
    - persistentvolumeclaims
    - ingresses
    verbs: 
    - create
    - delete
    - get
    - list
    - patch
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "var.fullname" . }}-oam-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "var.fullname" . }}-oam-rbac
subjects:
  - kind: ServiceAccount
    name: oam-kubernetes-runtime
    namespace: verrazzano-system
  - kind: ServiceAccount
    name: verrazzano-application-operator
    namespace: verrazzano-system
{{- end }}
