apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "var.fullname" . }}-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: /tmp
    server: 10.0.0.1
