kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "var.fullname" . }}-setup-config
data:
    01_setPassword.sh:
     "#!/bin/bash \n
      export DB_PASSWORD=$(cat /opt/oracle/oradata/tmppwd.txt) \n
      sqlplus / AS SYSDBA << EOF \n
      ALTER USER SYS IDENTIFIED BY \"$DB_PASSWORD\"; \n
      ALTER USER SYSTEM IDENTIFIED BY \"$DB_PASSWORD\"; \n
      ALTER SESSION SET CONTAINER=ORCLPDB1; \n
      ALTER USER PDBADMIN IDENTIFIED BY \"$DB_PASSWORD\"; \n
      exit; \n
      EOF \n
     "
    02_setupOML.sh: 
     "#!/bin/bash \n
      export DB_PASSWORD=$(cat /opt/oracle/oradata/tmppwd.txt) \n
      sqlplus sys/$DB_PASSWORD@127.0.0.1/ORCLPDB1:1521 as sysdba << EOF \n
      ALTER PROFILE DEFAULT LIMIT PASSWORD_VERIFY_FUNCTION NULL; \n
      @/opt/oracle/product/21c/dbhome_1/oml4py/server/pyqcfg.sql \n
      exit; \n
      EOF \n
     "
    03_cleanup.sh: 
     "#!/bin/bash \n
      rm /opt/oracle/oradata/tmppwd.txt \n
     "
