{{- if eq .Values.verrazzano.OAMdeploy true }}
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: {{ include "var.fullname" . }}-cloudbeaver
  annotations:
    version: v1.0.0
    description: "Virtual Analytical Room Raddauerzaehlstellen"
    var/component: cloudbeaver
    var/name: raddauerzaehlstellen
    var/shortdesc: 'Anwendungs-Stack mit Datenbank, Analysedaten und Analysewerkzeug,
      hier: Fahrrad-Durchlaufzahlen'
spec:
  components:
    - componentName: {{ include "var.fullname" . }}-cloudbeaver-pvc-comp
    - componentName: {{ include "var.fullname" . }}-cloudbeaver-comp
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: {{ include "var.fullname" . }}-cloudbeaver-ingress
            spec:
              rules:
              - paths:
                - path: /
                  pathType: Prefix
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: {{ include "var.fullname" . }}-jupyter
  annotations:
    version: v1.0.0
    description: "Virtual Analytical Room Raddauerzaehlstellen"
    var/component: jupyter
    var/name: raddauerzaehlstellen
    var/shortdesc: 'Anwendungs-Stack mit Datenbank, Analysedaten und Analysewerkzeug,
      hier: Fahrrad-Durchlaufzahlen'
spec:
  components:
    - componentName: {{ include "var.fullname" . }}-notebooks-pvc-comp
    - componentName: {{ include "var.fullname" . }}-jupyter-comp
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: {{ include "var.fullname" . }}-jupyter-ingress
            spec:
              rules:
              - paths:
                - path: /
                  pathType: Prefix
{{- end }}

