apiVersion: v1
kind: Service
metadata:
  name:  {{ include "var.fullname" . }}-jupyter
  annotations:
    var/component: Jupyter Notebook
    var/name: Fahrrad-Durchlaufzahlen
    var/shortdesc: 'Anwendungs-Stack mit Datenbank und Machine Learning, 
    dynamisch geladener Analysedaten und verknüpftem Analysewerkzeug'
spec:
  selector:
      {{- include "var.selectorLabels" . | nindent 6 }}
      component: jupyter
  ports:
    - port: 8889
      targetPort: 8889
      name: jupyter
  type: LoadBalancer

