apiVersion: v1
kind: Service
metadata:
  name:  {{ include "osa.fullname" . }}
  annotations:
    var/component: Stream Analytics UI
    var/name: Oracle Stream Analytics
    var/shortdesc: 'Anwendungs-Stack zur Analyse von Streaming-Daten
    auf Basis von Kafka, JMS oder GoldenGate'

spec:
  selector:
      {{- include "osa.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9080
      name: osa
  type: {{ .Values.service.type }}
